// Local-only PayPal sandbox subscription inspector and opt-in AI draft reviewer.
// Zero payment writes, customer messages, external notifications or production PayPal URLs.
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { DEMO, summarize, validId } from './logic.mjs';
import { isLocalBrowserRequest } from './local-boundary.mjs';

const PAYPAL = 'https://api-m.sandbox.paypal.com';
const OPENAI = 'https://api.openai.com/v1/chat/completions';
const PORT = Number(process.env.PORT || 8787);
let cachedToken, tokenExpires = 0, refreshPromise;

async function boundedJson(response, limit = 400_000) {
  if (!response.ok || response.status >= 300) throw new Error('Remote provider request failed: ' + response.status);
  if (!response.body) throw new Error('Remote provider returned no body');
  let chunks = [], bytes = 0;
  for await (const chunk of response.body) {
    bytes += chunk.length;
    if (bytes > limit) { await response.body.cancel().catch(() => {}); throw new Error('Provider response too large'); }
    chunks.push(chunk);
  }
  try { return JSON.parse(Buffer.concat(chunks).toString('utf8')); }
  catch { throw new Error('Provider JSON was malformed'); }
}

async function paypalToken() {
  if (!process.env.PAYPAL_CLIENT_ID || !process.env.PAYPAL_CLIENT_SECRET)
    throw new Error('PayPal sandbox credentials are not configured');
  if (cachedToken && Date.now() < tokenExpires) return cachedToken;
  if (!refreshPromise) {
    refreshPromise = (async () => {
      const auth = Buffer.from(process.env.PAYPAL_CLIENT_ID + ':' + process.env.PAYPAL_CLIENT_SECRET).toString('base64');
      const res = await fetch(PAYPAL + '/v1/oauth2/token', {
        method:'POST', headers:{Authorization:'Basic ' + auth,'Content-Type':'application/x-www-form-urlencoded'},
        body:'grant_type=client_credentials', signal:AbortSignal.timeout(12000), redirect:'manual',
      });
      const payload = await boundedJson(res);
      if (typeof payload.access_token !== 'string' || !payload.access_token)
        throw new Error('PayPal OAuth token missing');
      cachedToken = payload.access_token;
      tokenExpires = Date.now() + Math.max(0, Math.min(3000, Number(payload.expires_in || 0) - 60)) * 1000;
      return cachedToken;
    })().finally(() => { refreshPromise = null; });
  }
  return await refreshPromise;
}

async function paypalGet(path) {
  const token = await paypalToken();
  const res = await fetch(PAYPAL + path, {
    headers:{Authorization:'Bearer ' + token,Accept:'application/json'},
    signal:AbortSignal.timeout(12000), redirect:'manual',
  });
  return boundedJson(res);
}

function validateMode(mode) {
  if (mode !== 'demo' && mode !== 'sandbox') throw new Error('Invalid mode');
  return mode;
}
async function listing(mode) {
  if (mode === 'demo') return DEMO.map(x => ({id:x.id,status:x.status,plan_id:x.plan_id}));
  const value = await paypalGet('/v1/billing/subscriptions?page=1&page_size=20');
  if (!Array.isArray(value.subscriptions)) throw new Error('PayPal list format changed');
  return value.subscriptions.filter(x => validId(x?.id)).slice(0,20)
    .map(x => ({id:x.id,status:String(x.status || ''),plan_id:String(x.plan_id || '')}));
}
async function detail(mode,id) {
  if (!validId(id)) throw new Error('Invalid subscription ID');
  if (mode === 'demo') {
    const obj = DEMO.find(x => x.id === id);
    if (!obj) throw new Error('Demo subscription not found');
    return obj;
  }
  const value = await paypalGet('/v1/billing/subscriptions/' + encodeURIComponent(id) + '?fields=last_failed_payment');
  if (value.id !== id) throw new Error('PayPal returned mismatched subscription ID');
  return value;
}
async function reviewerDraft(facts) {
  if (!process.env.OPENAI_API_KEY) return {available:false,kind:'RULE_BASED_PREVIEW',
    text:'Review the verified current subscription status and ask the customer whether they want help. This preview is not generated by AI.'};
  // Only these non-PII fields cross the model boundary, not subscriber or account data.
  const minimal = {status:facts.status,tier:facts.tier,rationale:facts.rationale,
    next_billing_at:facts.next_billing_at,last_failed_at:facts.last_failed_at};
  const res = await fetch(OPENAI, {
    method:'POST', redirect:'manual', signal:AbortSignal.timeout(15000),
    headers:{Authorization:'Bearer ' + process.env.OPENAI_API_KEY,'Content-Type':'application/json'},
    body:JSON.stringify({
      model:process.env.OPENAI_MODEL || 'gpt-4o-mini', temperature:0.2, max_tokens:240,
      messages:[
        {role:'system',content:'You draft concise, respectful, optional customer-support notes. Never assert payment succeeded/failed beyond the supplied evidence. Never offer discounts, charge or send messages. No coercion. Output text under 500 characters.'},
        {role:'user',content:'Draft a human-review-only customer note from these sanitized PayPal sandbox subscription facts: ' + JSON.stringify(minimal)}
      ]
    })
  });
  const data = await boundedJson(res);
  const text = data.choices?.[0]?.message?.content;
  if (typeof text !== 'string' || !text.trim()) throw new Error('AI service returned no review draft');
  return {available:true,kind:'AI_GENERATED_UNSENT',text:text.slice(0,1000)};
}
function response(res,status,data) {
  res.writeHead(status, {
    'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',
    'X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'",
  });
  res.end(JSON.stringify(data));
}
async function incoming(req) {
  let bytes = 0, chunks = [];
  for await (const chunk of req) {
    bytes += chunk.length;
    if (bytes > 8192) throw new Error('Request too large');
    chunks.push(chunk);
  }
  try { return JSON.parse(Buffer.concat(chunks).toString('utf8')); }
  catch { throw new Error('Invalid request JSON'); }
}
export function makeServer() {
  return createServer(async (req,res) => {
    try {
      if (!isLocalBrowserRequest(req.headers))
        return response(res,403,{error:'Only same-origin local requests are supported'});
      const url = new URL(req.url || '/', 'http://localhost');
      if (req.method === 'GET' && url.pathname === '/') {
        const html = await readFile(new URL('../web/index.html',import.meta.url));
        res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store',
          'Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'",
          'X-Content-Type-Options':'nosniff'});
        return res.end(html);
      }
      if (req.method === 'GET' && url.pathname === '/app.js') {
        const code = await readFile(new URL('../web/app.js',import.meta.url));
        res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store',
          'X-Content-Type-Options':'nosniff'});
        return res.end(code);
      }
      if (req.method === 'GET' && url.pathname === '/api/list') {
        const mode = validateMode(url.searchParams.get('mode'));
        return response(res,200,{mode,items:await listing(mode)});
      }
      if (req.method === 'GET' && url.pathname === '/api/detail') {
        const mode = validateMode(url.searchParams.get('mode'));
        const item = summarize(await detail(mode,url.searchParams.get('id')));
        return response(res,200,{mode,receipt:item});
      }
      if (req.method === 'POST' && url.pathname === '/api/draft') {
        const body = await incoming(req);
        const mode = validateMode(body?.mode);
        const facts = summarize(await detail(mode,body?.id));
        if (!body?.fingerprint || body.fingerprint !== facts.fingerprint)
          return response(res,409,{error:'Subscription changed; refresh detail before drafting'});
        return response(res,200,{mode,receipt:facts,
          proposal:await reviewerDraft(facts),sent:false,modified_subscription:false});
      }
      response(res,404,{error:'Not found'});
    } catch(e) {
      response(res,/not configured/.test(e.message)?503:400,{error:String(e.message || 'Request failed').slice(0,180)});
    }
  });
}
if (import.meta.url === new URL('file://' + process.argv[1]).href) {
  if (!Number.isInteger(PORT) || PORT < 1024 || PORT > 65535) throw new Error('Invalid PORT');
  makeServer().listen(PORT,'127.0.0.1',() => console.log('RenewalGuard local: http://127.0.0.1:' + PORT));
}
