[package]
name = "workseal-escrow"
version = "0.1.0"
description = "WorkSeal PDA-controlled SPL escrow"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "workseal_escrow"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
anchor-debug = []
custom-heap = []
custom-panic = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "=1.2.0"
anchor-spl = "=1.2.0"
